Models/ErrorViewModel.cs
using System;

namespace GerenciadorDeUsuarios.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Permissao.cs
using System;
using System.Collections.Generic;

namespace GerenciadorDeUsuarios.Models
{
    public class Permissao
    {
        public Guid PermissaoId { get; set; }
        public string Nome { get; set; }
        public IList<PermissoesUsuario> PermissoesUsuario { get; set; }
    }
}

Models/PermissoesUsuario.cs
using System;

namespace GerenciadorDeUsuarios.Models
{
    public class PermissoesUsuario
    {
        public Guid UsuarioId { get; set; }
        public Usuario Usuario { get; set; }
        public Guid PermissaoId { get; set; }
        public Permissao Permissao { get; set; }
    }
}

Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GerenciadorDeUsuarios.Models
{
    public class Usuario
    {
        public Guid UsuarioId { get; set; }

        [Required(ErrorMessage = "Este campo não pode estar vazio!")]
        [MaxLength(100, ErrorMessage = "Tamanho maximo de 100 caracteres!")]
        public string Nome { get; set; }
        
        [Required(ErrorMessage = "Este campo não pode estar vazio!")]
        [MaxLength(255, ErrorMessage = "Tamanho maximo de 255 caracteres!")]
        public string Email { get; set; }
        
        [Required(ErrorMessage = "Este campo não pode estar vazio!")]
        [StringLength(10, MinimumLength = 3, ErrorMessage = "Quantidade de caracteres não permitida!")]
        public string Senha { get; set; }
        
        public IList<PermissoesUsuario> PermissoesUsuario { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GerenciadorDeUsuarios.Models;

namespace GerenciadorDeUsuarios.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UsuarioController.cs
using System;
using System.Threading.Tasks;
using GerenciadorDeUsuarios.Models;
using GerenciadorDeUsuarios.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace GerenciadorDeUsuarios.Controllers
{
    public class UsuarioController : Controller
    {
        public IRepositorioBase<Usuario> Usuarios { get; }
        public UsuarioController(IRepositorioBase<Usuario> usuarios)
        {
            this.Usuarios = usuarios;
        }
        public async Task<IActionResult> Todos()
        {
            var usuarios = await Usuarios.GetALL();
            return View(usuarios);
        }

        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Novo([FromForm]Usuario usuario)
        {
            if(ModelState.IsValid)
            {
                await Usuarios.Save(usuario);
                return RedirectToAction("Todos");
            }
            else
            {
                return View();
            }                
            
        }

        public async Task<IActionResult> Editar(Guid id)
        {
            var usuario  = await Usuarios.GetById(id);
            return View(usuario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar([FromForm]Usuario usuario, Guid id)
        {
            usuario.UsuarioId = id;
            await Usuarios.Update(usuario);
            return RedirectToAction("Todos");
        }

        public async Task<IActionResult> Deletar(Guid id)
        {
            var usuario  = await Usuarios.GetById(id);
            return View(usuario);
        }

        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmacaoDeletar(Guid id)
        {
            await Usuarios.Delete(id);
            return RedirectToAction("Todos");
        }

    }   
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GerenciadorDeUsuarios</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Usuario" asp-action="Todos" class="navbar-brand">GerenciadorDeUsuarios</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Usuario" asp-action="Todos">Usuario</a></li>
                    <!--<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>-->
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <br>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - GerenciadorDeUsuarios</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_UsuarioForm.cshtml
@model Usuario

	<div class="row">
		<div class="col-md-4">
		</div>
		<div class="col-md-4">
			<form method="POST">
                @Html.AntiForgeryToken()
				<div class="form-group">
					<label asp-for="@Model.Nome">Nome</label>
					<input type="text" asp-for="Nome" placeholder="Nome do Usuário" class="form-control" >
                    <span class="text-danger" asp-validation-for="@Model.Nome"></span>
				</div>
				<div class="form-group">
					<label asp-for="@Model.Email">Email</label>
					<input type="email" asp-for="Email" placeholder="Email do Usuário" class="form-control" >
                    <span class="text-danger" asp-validation-for="@Model.Email"></span>
				</div>
				<div>
					<label asp-for="@Model.Senha">Senha</label>
					<input type="password" asp-for="Senha" placeholder="Senha do Usuário" class="form-control" >
                    <span class="text-danger" asp-validation-for="@Model.Senha"></span>
				</div>
				<br>
				<button type="submit" class="btn btn-success">
					Salvar
				</button>
			</form>
		</div>
		<div class="col-md-4">
		</div>
	</div>

Views/Usuario/Deletar.cshtml
@model Usuario


<div class="row">
    
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <label> Nome: @Model.Nome</label>
        <label> Email: @Model.Email</label>
        <form asp-controller="Usuario" asp-action="Deletar">
            <label> Quer realmente deletar?</label>
            <button type="submit" class="btn btn-primary">Sim</button>
            
            <a class="btn btn-danger" asp-action="Todos">Não</a>
        </form>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        
    </div>
    
</div>

Views/Usuario/Editar.cshtml
@model Usuario
@await Html.PartialAsync("_UsuarioForm", Model)

Views/Usuario/Novo.cshtml
@model Usuario
@await Html.PartialAsync("_UsuarioForm", Model)

Views/Usuario/Todos.cshtml
@model IList<Usuario>


<div class="row">
    <a class="btn btn-info" asp-action="Novo"><spam class="glyphicon glyphicon-plus"></spam></a>
    <br>
</div>

<div class="row">    
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th class="text-center">Nome</th>
                <th class="text-center">Email</th>
                <th class="text-center"></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var usuario in @Model)
            {
                <tr>
                    <td>@usuario.Nome</td>
                    <td>@usuario.Email</td>
                    <td class="text-center">
                        <a class="btn btn-primary" asp-controller="Usuario" asp-action="Editar" asp-route-id="@usuario.UsuarioId"><spam class="glyphicon glyphicon-pencil"></spam></a>
                        <a class="btn btn-danger" asp-controller="Usuario" asp-action="Deletar" asp-route-id="@usuario.UsuarioId"><spam class="glyphicon glyphicon-remove"></spam></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>